#!/usr/bin/env bash
# gate.sh <tier> — this repo's definition of done.
#
# GENERATED by `loom.sh init` from the tooling found in this repo, then edited
# by a human. Runs in CI, in a bare clone, and in a lane's worktree, identically.
#
# Tiers widen scope; they never soften it. Every tier runs the checks above it.
# The split below is a STARTING POINT: move a check into a narrower tier when it
# is slow, and add the ones detection cannot see (integration, migrations, a11y).
set -euo pipefail
cd "$(dirname "$0")/.."

tier="${1:?usage: gate.sh <docs|logic|api|ui>}"
case "$tier" in docs|logic|api|ui) ;; *) echo "gate: unknown tier '$tier'" >&2; exit 2 ;; esac

run() { echo "gate: $*"; "$@"; }

run pnpm lint
run pnpm test
echo "gate: $tier ok"
